# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blob.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='blob.proto',
  package='service',
  syntax='proto3',
  serialized_options=b'Z\nservice/go',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nblob.proto\x12\x07service\"\xc1\x01\n\tBlobValue\x12\x17\n\rboolean_value\x18\x01 \x01(\x08H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\'\n\nlist_value\x18\x05 \x01(\x0b\x32\x11.service.BlobListH\x00\x12%\n\tmap_value\x18\x06 \x01(\x0b\x32\x10.service.BlobMapH\x00\x42\x07\n\x05value\"z\n\x07\x42lobMap\x12,\n\x06values\x18\x01 \x03(\x0b\x32\x1c.service.BlobMap.ValuesEntry\x1a\x41\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.service.BlobValue:\x02\x38\x01\".\n\x08\x42lobList\x12\"\n\x06values\x18\x01 \x03(\x0b\x32\x12.service.BlobValueB\x0cZ\nservice/gob\x06proto3'
)




_BLOBVALUE = _descriptor.Descriptor(
  name='BlobValue',
  full_name='service.BlobValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boolean_value', full_name='service.BlobValue.boolean_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='service.BlobValue.int_value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='service.BlobValue.string_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='service.BlobValue.float_value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='list_value', full_name='service.BlobValue.list_value', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_value', full_name='service.BlobValue.map_value', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='service.BlobValue.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=24,
  serialized_end=217,
)


_BLOBMAP_VALUESENTRY = _descriptor.Descriptor(
  name='ValuesEntry',
  full_name='service.BlobMap.ValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='service.BlobMap.ValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='service.BlobMap.ValuesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=341,
)

_BLOBMAP = _descriptor.Descriptor(
  name='BlobMap',
  full_name='service.BlobMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='service.BlobMap.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BLOBMAP_VALUESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=341,
)


_BLOBLIST = _descriptor.Descriptor(
  name='BlobList',
  full_name='service.BlobList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='service.BlobList.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=389,
)

_BLOBVALUE.fields_by_name['list_value'].message_type = _BLOBLIST
_BLOBVALUE.fields_by_name['map_value'].message_type = _BLOBMAP
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['boolean_value'])
_BLOBVALUE.fields_by_name['boolean_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['int_value'])
_BLOBVALUE.fields_by_name['int_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['string_value'])
_BLOBVALUE.fields_by_name['string_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['float_value'])
_BLOBVALUE.fields_by_name['float_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['list_value'])
_BLOBVALUE.fields_by_name['list_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBVALUE.oneofs_by_name['value'].fields.append(
  _BLOBVALUE.fields_by_name['map_value'])
_BLOBVALUE.fields_by_name['map_value'].containing_oneof = _BLOBVALUE.oneofs_by_name['value']
_BLOBMAP_VALUESENTRY.fields_by_name['value'].message_type = _BLOBVALUE
_BLOBMAP_VALUESENTRY.containing_type = _BLOBMAP
_BLOBMAP.fields_by_name['values'].message_type = _BLOBMAP_VALUESENTRY
_BLOBLIST.fields_by_name['values'].message_type = _BLOBVALUE
DESCRIPTOR.message_types_by_name['BlobValue'] = _BLOBVALUE
DESCRIPTOR.message_types_by_name['BlobMap'] = _BLOBMAP
DESCRIPTOR.message_types_by_name['BlobList'] = _BLOBLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlobValue = _reflection.GeneratedProtocolMessageType('BlobValue', (_message.Message,), {
  'DESCRIPTOR' : _BLOBVALUE,
  '__module__' : 'blob_pb2'
  # @@protoc_insertion_point(class_scope:service.BlobValue)
  })
_sym_db.RegisterMessage(BlobValue)

BlobMap = _reflection.GeneratedProtocolMessageType('BlobMap', (_message.Message,), {

  'ValuesEntry' : _reflection.GeneratedProtocolMessageType('ValuesEntry', (_message.Message,), {
    'DESCRIPTOR' : _BLOBMAP_VALUESENTRY,
    '__module__' : 'blob_pb2'
    # @@protoc_insertion_point(class_scope:service.BlobMap.ValuesEntry)
    })
  ,
  'DESCRIPTOR' : _BLOBMAP,
  '__module__' : 'blob_pb2'
  # @@protoc_insertion_point(class_scope:service.BlobMap)
  })
_sym_db.RegisterMessage(BlobMap)
_sym_db.RegisterMessage(BlobMap.ValuesEntry)

BlobList = _reflection.GeneratedProtocolMessageType('BlobList', (_message.Message,), {
  'DESCRIPTOR' : _BLOBLIST,
  '__module__' : 'blob_pb2'
  # @@protoc_insertion_point(class_scope:service.BlobList)
  })
_sym_db.RegisterMessage(BlobList)


DESCRIPTOR._options = None
_BLOBMAP_VALUESENTRY._options = None
# @@protoc_insertion_point(module_scope)
